name: Deploy to Lightsail

on:
  push:
    branches:
      - master  # ensure it only deploys when pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }} # Static IP added as a Secret
          username: bitnami # Default user for Lightsail Nginx
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }} # .pem key 
          script: |
            cd /opt/bitnami/nginx/html
            git pull origin master
